/**
 * Kameron Hinman-Mitchell
 * CS-320
 * October 2025
 */
package org.snhu.cs320.appointment;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import java.util.Date;
import java.util.Calendar;
import java.util.Map;

class AppointmentServiceTest{
    
    private AppointmentService appointmentService;
    private Date futureDate;
    private String validDescription;
    
    @BeforeEach
    void setUp() {
        appointmentService = new AppointmentService();
        
        Calendar futureCal = Calendar.getInstance();
        futureCal.set(Calendar.YEAR, 2026);
        futureDate = futureCal.getTime();
        
        validDescription = "Valid appointment description";
    }

    @Test
    @DisplayName("Add Appointment with Auto-Generated ID")
    void testAddAppointmentWithAutoGeneratedId() {
        String appointmentId = appointmentService.addAppointment(futureDate, validDescription);
        
        assertNotNull(appointmentId);
        assertTrue(appointmentService.appointmentExists(appointmentId));
        assertEquals(1, appointmentService.getAppointmentCount());
        
        Appointment retrieved = appointmentService.getAppointment(appointmentId);
        assertEquals(futureDate, retrieved.getAppointmentDate());
        assertEquals(validDescription, retrieved.getDescription());
    }
    
    @Test
    @DisplayName("Add Appointment with Specific ID")
    void testAddAppointmentWithSpecificId() {
        String specificId = "SPECIFIC1";
        appointmentService.addAppointment(specificId, futureDate, validDescription);
        
        assertTrue(appointmentService.appointmentExists(specificId));
        Appointment retrieved = appointmentService.getAppointment(specificId);
        assertEquals(specificId, retrieved.getAppointmentId());
    }
    
    @Test
    @DisplayName("Add Duplicate Appointment ID")
    void testAddDuplicateAppointmentId() {
        String duplicateId = "DUPLICATE";
        appointmentService.addAppointment(duplicateId, futureDate, validDescription);
        
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            appointmentService.addAppointment(duplicateId, futureDate, "Different description");
        });
        
        assertTrue(exception.getMessage().contains("already exists"));
    }
    
    @Test
    @DisplayName("Delete Existing Appointment")
    void testDeleteExistingAppointment() {
        String appointmentId = appointmentService.addAppointment(futureDate, validDescription);
        
        assertTrue(appointmentService.appointmentExists(appointmentId));
        
        boolean deleted = appointmentService.deleteAppointment(appointmentId);
        assertTrue(deleted);
        assertFalse(appointmentService.appointmentExists(appointmentId));
        assertEquals(0, appointmentService.getAppointmentCount());
    }
    
    @Test
    @DisplayName("Delete Non-Existent Appointment")
    void testDeleteNonExistentAppointment() {
        boolean deleted = appointmentService.deleteAppointment("NON_EXISTENT");
        assertFalse(deleted);
    }
    
    @Test
    @DisplayName("Delete with Null ID")
    void testDeleteWithNullId() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            appointmentService.deleteAppointment(null);
        });
        
        assertTrue(exception.getMessage().contains("cannot be null"));
    }
    
    @Test
    @DisplayName("Get Existing Appointment")
    void testGetExistingAppointment() {
        String appointmentId = appointmentService.addAppointment(futureDate, validDescription);
        
        Appointment retrieved = appointmentService.getAppointment(appointmentId);
        assertNotNull(retrieved);
        assertEquals(appointmentId, retrieved.getAppointmentId());
        assertEquals(validDescription, retrieved.getDescription());
    }
    
    @Test
    @DisplayName("Get Non-Existent Appointment")
    void testGetNonExistentAppointment() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            appointmentService.getAppointment("NON_EXISTENT");
        });
        
        assertTrue(exception.getMessage().contains("not found"));
    }
    
    @Test
    @DisplayName("Update Appointment Date")
    void testUpdateAppointmentDate() {
        String appointmentId = appointmentService.addAppointment(futureDate, validDescription);
        
        Calendar newFutureCal = Calendar.getInstance();
        newFutureCal.set(Calendar.YEAR, 2027);
        Date newFutureDate = newFutureCal.getTime();
        
        appointmentService.updateAppointmentDate(appointmentId, newFutureDate);
        
        Appointment updated = appointmentService.getAppointment(appointmentId);
        assertEquals(newFutureDate, updated.getAppointmentDate());
    }
    
    @Test
    @DisplayName("Update Appointment Description")
    void testUpdateAppointmentDescription() {
        String appointmentId = appointmentService.addAppointment(futureDate, validDescription);
        String newDescription = "Updated description";
        
        appointmentService.updateAppointmentDescription(appointmentId, newDescription);
        
        Appointment updated = appointmentService.getAppointment(appointmentId);
        assertEquals(newDescription, updated.getDescription());
    }
    
    @Test
    @DisplayName("Get All Appointments")
    void testGetAllAppointments() {
        appointmentService.addAppointment("ID1", futureDate, "Description 1");
        appointmentService.addAppointment("ID2", futureDate, "Description 2");
        
        Map<String, Appointment> allAppointments = appointmentService.getAllAppointments();
        
        assertEquals(2, allAppointments.size());
        assertTrue(allAppointments.containsKey("ID1"));
        assertTrue(allAppointments.containsKey("ID2"));
    }
    
    @Test
    @DisplayName("Clear All Appointments")
    void testClearAllAppointments() {
        appointmentService.addAppointment(futureDate, validDescription);
        appointmentService.addAppointment(futureDate, "Another description");
        
        assertEquals(2, appointmentService.getAppointmentCount());
        
        appointmentService.clearAllAppointments();
        
        assertEquals(0, appointmentService.getAppointmentCount());
    }
    
    @Test
    @DisplayName("Multiple Safety Test")
    void testMultipleOperations() {
        // Test adding multiple appointments
        String id1 = appointmentService.addAppointment(futureDate, "First appointment");
        String id2 = appointmentService.addAppointment(futureDate, "Second appointment");
        
        assertEquals(2, appointmentService.getAppointmentCount());
        assertTrue(appointmentService.appointmentExists(id1));
        assertTrue(appointmentService.appointmentExists(id2));
        
        // Test deletion
        appointmentService.deleteAppointment(id1);
        assertEquals(1, appointmentService.getAppointmentCount());
        assertFalse(appointmentService.appointmentExists(id1));
        assertTrue(appointmentService.appointmentExists(id2));
        
        // Test update
        String newDescription = "Updated second appointment";
        appointmentService.updateAppointmentDescription(id2, newDescription);
        
        Appointment updated = appointmentService.getAppointment(id2);
        assertEquals(newDescription, updated.getDescription());
    }
}