/**
 * Kameron Hinman-Mitchell
 * CS-320
 * September 2025
 * Updated May 2026
 */

package org.snhu.cs320.task;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class TaskServiceTest {
    
    private TaskService taskService;
    private final String validTaskName = "Test Task";
    private final String validDescription = "Test Description";
    
    @BeforeEach
    void setUp() {
        taskService = new TaskService();
    }
    
    @Test
    @DisplayName("Add task with auto-generated ID")
    void testAddTask() {
        taskService.addTask(validTaskName, validDescription);
        
        Map<String, Task> tasks = taskService.getAllTasks();
        assertEquals(1, tasks.size());
        
        Task addedTask = tasks.values().iterator().next();
        assertEquals(validTaskName, addedTask.getTaskName());
        assertEquals(validDescription, addedTask.getDescription());
        assertNotNull(addedTask.getTaskId());
    }
    
    @Test
    @DisplayName("Add multiple tasks with auto-generated IDs")
    void testAddMultipleAutoGeneratedTasks() {
        taskService.addTask("Task 1", "Desc 1");
        taskService.addTask("Task 2", "Desc 2");
        taskService.addTask("Task 3", "Desc 3");
        
        Map<String, Task> tasks = taskService.getAllTasks();
        assertEquals(3, tasks.size());
        
        String[] ids = tasks.keySet().toArray(new String[0]);
        assertNotEquals(ids[0], ids[1]);
        assertNotEquals(ids[0], ids[2]);
        assertNotEquals(ids[1], ids[2]);
    }
    
    @Test
    @DisplayName("Add task with specific ID")
    void testAddTaskWithSpecificId() {
        String specificId = "TASK001";
        taskService.addTaskWithId(specificId, validTaskName, validDescription);
        
        Task retrievedTask = taskService.getTaskById(specificId);
        assertNotNull(retrievedTask);
        assertEquals(specificId, retrievedTask.getTaskId());
        assertEquals(validTaskName, retrievedTask.getTaskName());
    }
    
    @Test
    @DisplayName("Add task with duplicate ID throws exception")
    void testAddTaskWithDuplicateId() {
        String duplicateId = "TASK001";
        taskService.addTaskWithId(duplicateId, validTaskName, validDescription);
        
        assertThrows(IllegalArgumentException.class, () -> {
            taskService.addTaskWithId(duplicateId, "Another Task", "Another Description");
        });
    }
    
    @Test
    @DisplayName("Delete existing task")
    void testDeleteExistingTask() {
        String taskId = "TASK001";
        taskService.addTaskWithId(taskId, validTaskName, validDescription);
        
        assertTrue(taskService.getAllTasks().containsKey(taskId));
        
        taskService.deleteTask(taskId);
        
        assertFalse(taskService.getAllTasks().containsKey(taskId));
    }
    
    @Test
    @DisplayName("Delete non-existent task throws exception")
    void testDeleteNonExistentTask() {
        assertThrows(IllegalArgumentException.class, () -> {
            taskService.deleteTask("NON_EXISTENT");
        });
    }
    
    @Test
    @DisplayName("Update task name")
    void testUpdateTaskName() {
        String taskId = "TASK001";
        taskService.addTaskWithId(taskId, validTaskName, validDescription);
        
        String newTaskName = "Updated Task Name";
        taskService.updateTaskName(taskId, newTaskName);
        
        Task updatedTask = taskService.getTaskById(taskId);
        assertEquals(newTaskName, updatedTask.getTaskName());
        assertEquals(validDescription, updatedTask.getDescription());
    }
    
    @Test
    @DisplayName("Update task description")
    void testUpdateTaskDescription() {
        String taskId = "TASK001";
        taskService.addTaskWithId(taskId, validTaskName, validDescription);
        
        String newDescription = "Updated description";
        taskService.updateTaskDescription(taskId, newDescription);
        
        Task updatedTask = taskService.getTaskById(taskId);
        assertEquals(validTaskName, updatedTask.getTaskName());
        assertEquals(newDescription, updatedTask.getDescription());
    }
    
    @Test
    @DisplayName("Update both name and description together")
    void testUpdateBothNameAndDescription() {
        String taskId = "TASK001";
        taskService.addTaskWithId(taskId, "Original Name", "Original Desc");
        
        taskService.updateTaskName(taskId, "New Name");
        taskService.updateTaskDescription(taskId, "New Desc");
        
        Task task = taskService.getTaskById(taskId);
        assertEquals("New Name", task.getTaskName());
        assertEquals("New Desc", task.getDescription());
    }
    
    @Test
    @DisplayName("Update non-existent task name throws exception")
    void testUpdateTaskNameNotFound() {
        assertThrows(IllegalArgumentException.class, () -> {
            taskService.updateTaskName("NON_EXISTENT", "New Name");
        });
    }
    
    @Test
    @DisplayName("Update non-existent task description throws exception")
    void testUpdateTaskDescriptionNotFound() {
        assertThrows(IllegalArgumentException.class, () -> {
            taskService.updateTaskDescription("NON_EXISTENT", "New Description");
        });
    }
    
    @Test
    @DisplayName("Get task by ID returns correct task")
    void testGetTaskById() {
        taskService.addTaskWithId("ID1", "Task One", "Desc One");
        taskService.addTaskWithId("ID2", "Task Two", "Desc Two");
        
        Task task = taskService.getTaskById("ID2");
        assertEquals("ID2", task.getTaskId());
        assertEquals("Task Two", task.getTaskName());
    }
    
    @Test
    @DisplayName("Get non-existent task throws exception")
    void testGetNonExistentTask() {
        assertThrows(IllegalArgumentException.class, () -> {
            taskService.getTaskById("NON_EXISTENT");
        });
    }
    
    @Test
    @DisplayName("Clear all tasks")
    void testClearAllTasks() {
        taskService.addTask("Task 1", "Description 1");
        taskService.addTask("Task 2", "Description 2");
        
        assertEquals(2, taskService.getAllTasks().size());
        
        taskService.clearAllTasks();
        
        assertEquals(0, taskService.getAllTasks().size());
    }
}